version: "3.8"

services:
  pspace:
    container_name: pspace_cnt
    build: .
    image: pspace_img
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    deploy:
        resources:
            reservations:
                devices:
                - driver: nvidia
                  count: all
                  capabilities: [gpu, compute, utility, graphics, compat32, video, display]
    volumes:
      - "./hw1:/workspace/hw1"
      - "./hw2:/workspace/hw2"
      - "/tmp/.X11-unix/:/tmp/.X11-unix/:rw"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      # Choose one of the following two lines for your dataset path
      # - "./datasets/KITTI:/workspace/datasets/KITTI"
      - "/mnt/01D66F5B1654EDA0/KITTI:/workspace/datasets/KITTI"
      
    